### ISSUE TITLE
Python 3 - unreliable failing behavior

### ISSUE THREAD

**Issue by vaab** [vaab/gitchangelog#27]
When launching gitchangelog on my python 3.4.2, I get sometimes full changelog, but sometimes it's empty, and other times it bails out with this traceback::

```
Traceback (most recent call last):
  File "./gitchangelog", line 1052, in <module>
    main()
  File "./gitchangelog", line 1034, in main
    subject_process=config.get("subject_process", noop),
  File "./gitchangelog", line 860, in changelog
    for tag in reversed(repository.tags)
  File "./gitchangelog", line 605, in tags
    key=lambda x: int(x.committer_date_timestamp))
  File "./gitchangelog", line 605, in <lambda>
    key=lambda x: int(x.committer_date_timestamp))
ValueError: invalid literal for int() with base 10: 'tag 0.1.0\nTagger: Valentin Lab <valentin.lab@securactive.net>\n\nInitial release\n\n1309333456'
```

Could this come from the ``Phile`` and subprocess piping ?

**Comment by toninlg** [comment]
Hi,
I'm using https://github.com/git-for-windows which gives git in windows with msys2 environment. I added python 3.3.3 to it. Whit this environment gitchangelog works on Windows, but I have the same behavior as you, sometimes it works, sometimes it failed. I already had the two following errors:

>    error1: float(self.author_date_timestamp))
    ValueError: could not convert string to float: 'tag v1.1\nTagger: xxx \n\nTagging version 1.1\n\n1430061838'

 >   error2: key=lambda x: int(x.committer_date_timestamp))
    ValueError: invalid literal for int() with base 10: 'tag v1.0\nTagger: xxx \n\nTagging version 1.0\n\n1430046846'

I try to debug it a little, but I have never used python. What is strange to me is that with the same repository from one run to another one, the arguments sent in --pretty=format for git show -s are not always in the same order.

Thanks.

**Comment by rschoon** [comment]
I think this is actually a different problem that is only revealed by hash randomization.

On python2.7, the used git command is always `git show -s 0.1.0 --pretty=format:%b%x00%H%x00%ct%x00%B%x00%cn%x00%ad%x00%at%x00%an%x00%s --`. 

On python3, the command is random and a specific failing command is `git show -s 0.1.0 --pretty=format:%ct%x00%ad%x00%b%x00%s%x00%H%x00%B%x00%an%x00%at%x00%cn --`.

It's actually possible to reproduce on python2.7 if you pass the -R flag to python, as hash randomization was implemented but is not on by default.

You may have already noticed that in the failing command, %ct is the first field, which is one of the timestamp fields.  When git show on an annotated tag, we're getting the tag contents prepended as well (despite providing the custom format).  For example (the string literal that gitchangelog gets): 'tag 0.1.0\nTagger: Valentin Lab <valentin.lab@securactive.net>\n\nInitial release\n\n1309333456\x00Wed Mar 30 17:52:31 2011 +0200\x00Valentin Lab\x00\x00new: dev: Added ``git-changelog`` which converts git log history to a changelog provided a config file.\n\x0068557ceb0eb255d8e700b1e0fb61b6f1f24c3447\x00Valentin Lab\x001301500351\x00new: dev: Added ``git-changelog`` which converts git log history to a changelog provided a config file.'

I've spent a little bit of time digging into trying to find an actual solution.  So far the best I've come up with is to add another "%00" to the beginning of the format string so that the extra text can be easily ignored, but there's probably a better solution.

I've seen the empty changelog issue as well, but haven't tried digging into that one yet.  It might be the same type of problem, but working around this specific instance doesn't seem to help.

**Comment by vaab** [comment]
Thanks for your insights here, they are definitively valuable.
And actually, I found the fix thanks to your ping and your information.

It's actually ``git show`` that was a poor choice for displaying info on a commit. It seems much better to use ``git log`` as it won't display that prefix information that you've seen. That behavior is normal and is documented on the man page of ``git show`` and seems to me ill-advised, but nevertheless this is present and there seem to be no way to ask for ``git show`` to treat the reference as a standard reference and avoid detecting this as a tag and print its garbage about this tag.
