### ISSUE TITLE
Add support for "git log --first-parent"

### ISSUE THREAD

**Issue by kminh** [vaab/gitchangelog#44]
I think `--first-parent` can be a great companion to the `include_merge` option, i.e. include ONLY a merge commit and no other commits in the same merge bubble.

An example use case:
```
* Merge commit: This is a new feature... (summarize the new feature)
\ * Child of merge commit: fix: Fix something
\ * Child of merge commit: new: Add something
\ * Child of merge commit: chg: Change something
```
If I choose to include merge commit now it will split these 4 commits into different sections, while they most make sense when grouped together. Actually all the things a user needs to know when reading the changelog is already summarized in the merge commit.

I hope that makes sense.

Have been using this tool with great success recently (with a heavily modified mako template though).

**Comment by vaab** [comment]
Thank you for your feedback and your interest. If you think your mako template could makes sense for other people, please share it ! I would be definitively interested to provide more alternatives in ``gitchangelog``'s base package.
And for you main topic, are you suggesting to add a configuration option ``first_parent``, available along the ``include_merge``, that would simply activate a ``--first-parent`` flag into the ``git log`` command ?

That seems doable in a first view.

For your example use case, actually, it seems that ``include_merge = false`` allows the reverse of what you describe: the information is taken from the independant merge commits and the Merge commit itself must then be ignored. This way of seeing is partely due to the fact that otherwise, you need to actually write the content of the merge commit, and you'll repeat yourself in some ways. This also requires that you do some extra work while committing.

But I'm a true believer that best solution does not exists: I support the idea that gitchangelog should adapt to your workflow, and I'm totally ready to include a ``first_parent`` options would there be a PR coming. And I might include it myself as it is quite easy to implement... If ever you want to give it a try, do not forget to add doc and tests.

You can also give the feature a reality check: just add ``--first-parent`` in the source code in the ``log()`` method. And check if all is working as expected from your point of view.

Feel free also to give me more feedback with a complete example, because I'm not really sure I understood your workflow (and anything you would produce around this could be used to write the test and the doc). A simple use case with the given history, along with the gitchangelog entry you expect would be enough.

**Comment by vaab** [comment]
Ok, without any more feedback from your side, I'll have to close this issue. Feel free to repon and answer my question so we can make sure I have identified your issue. Thanks for your interest.
