### ISSUE TITLE
"git describe --tags" use question

### ISSUE THREAD

**Issue by FlYnN91** [vaab/gitchangelog#45]
Hi,

I am trying to setup gitchangelog and I've noticed that I am getting an error on the initial run off ./autorun.sh

The error I am getting is at line 185.
```
if ! "$git" describe --tags >/dev/null 2>&1; then
    die "Didn't find a git repository (or no tags found). " \
     "\`\`./autogen.sh\`\` uses git to create changelog and version information."
fi
```

However if I change `describe --tags` to `log` the script runs fine with no errors.

So just a question, what is t the script trying to do here? I understand that its trying to check for git, but is there a specific reason why describe does not work and log does?

Thanks

**Comment by vaab** [comment]
Hum, what is your git version ?

This script will use this exact command to fetch the current version of the code and put it in files that needs to get the version set up. It's a nice way also in this place to ensure the script will function correctly and print some help to you, it's a small sanity check in some ways.

The files that will be changed are listed in ".package". For instance, there's the ``gitchangelog.py`` code that manage the ``--version`` that gets outputed, the ``setup.py`` in case you do a ``python setup.py install`` ... etc...

AFAIK, ``git describe --tags`` should work on any repository **with tags**. Can you check what happens when you launch this command yourself ? It only tries to give you a nice version information based on last tag.

Did this answer your questions ? Many thanks for you interest.

**Comment by vaab** [comment]
I'll have to close this issue due to the fact that no clear issue really remains and my questions are remaining without answers. Feel free to re-open or comment anyway. Thanks for you interest.
