### ISSUE TITLE
Unable to use gitchangelog under travis builds

### ISSUE THREAD

**Issue by ssbarnea** [vaab/gitchangelog#51]
I tried to use `gitchangelog` as part of the build scripts executed via travis but I discovered that it does not work as expected.

First problem is that `pip install gitchangelog` failed with the error below:
```
 Command "/home/travis/virtualenv/python2.7.9/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-I7WzDd/gitchangelog/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KMZBF0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python2.7.9/include/site/python2.7" failed with error code 1 in /tmp/pip-build-I7WzDd/gitchangelog
```
Full logs at https://travis-ci.org/pycontribs/jira/jobs/150580836

The second problem is that it seems that is not possible to call `gitchangelog` as a python module which is a real PITA. Why? Installing command line utilities via pip does not work very well in all environments (especially on Windows or different virtual environments). For this reason most Python package developers do allow you to call modules using `python -m modulename [options]`. This works very well and allows you to use a specific python interpreter, always knowing which one you are calling.

This can be implemented with only few lines of code. Few examples of projects that are using this approach `pip`, `flake8`, `py.test`, `tox`,...

**Comment by vaab** [comment]
Hi, many thanks for your feedback !

There is very little information in the full logs of travis here, and we might need more than a simple "exited with errorlevel 1". How can we help here ? What is the content of ``/tmp/pip-KMZBF0-record/install-record.txt`` ?

For your second problem, (first, a separate issue is welcome if these subject are separate), can you be more precise on what you have tried and didn't work ? I'm asking this because:
- ``python -m gitchangelog OPTIONS`` is definitively working... 
- ``gitchangelog`` will also use your active python version, whatever it is thanks to the shebang line ``#!/usr/bin/env python`` (so this works perfectly inside virtualenv without using ``python -m modulename``)
- At last, ``python gitchangelog.py OPTIONS`` works also, as any other programs if you which a third way to NOT use your current active python version for instance, and I don't really see the difference in the context you've given to us with ``python -m gitchangelog OPTIONS``.

All this works fine in a basic linux installation, and I'm adding this information because it might help us understand what's wrong.

So to be clear: what makes you thing that ``it seems that is not possible to call gitchangelog as a python module`` ? What did you try ? and what did you expect ?

**Comment by vaab** [comment]
I'll take your silence as a good news that you managed to get through your issues. If it is not the case and/or you feel that you can help us improve ``gitchangelog`` in any way (more doc, feature proposal, suspected or verified bug) with any feedback, feel free to.
I'm closing this issue for the moment as there's no clear task for me here as I lack answers to my questions to move forward.
If you feel that I missed something, feel free to comment and reopen this issue !
