### ISSUE TITLE
Changelog for 3.0.0

### ISSUE THREAD

**Issue by tuukkamustonen** [vaab/gitchangelog#75]
Congratz on releasing 3.0.0! Gotta try it out.

I might be blind, but I can't seem to find changelog for `gitchangelog` (how twisted is that). Do you plan to add one (for this and future versions)?

**Comment by vaab** [comment]
The changelog is on [Pypi](https://pypi.python.org/pypi/gitchangelog). If you have the source you can get it by typing ``gitchangelog``.
There are basically 2 ways of seeing changelog:

- either you think it is duplicate information (at least in the source code) with the accessible git history. So 
  you  generate it only for the docs (on pypi for instance).

- either you want to store a version of your changelog along your source, in this case, I guess the
  incremental changelog recipe is for you, because you can keep and update the file and make tweaks 
  whenever you want : doing such, you add valuable information to your changelog and this justifies why
  you would like to store it along with your source code.

As you guessed, ``gitchangelog`` (the project) itself uses the first perspective. The tool ``gitchangelog`` is malleable enough to support you in either way.

Did I answer you question ?

**Comment by tuukkamustonen** [comment]
Phew, I wasn't blind, I just have bad eyes.

Yeah, the answer makes totally sense (good point about duplicate information).

Incremental changelog sounds interesting, though it sounds like it will always lag one commit behind?

**Comment by vaab** [comment]
I'm not sure to understand what you mean. The incremental changelog recipe allows you to update an existing Changelog file by inserting inplace the last commit/tag that are missing from it (it could be several tags, or yet unreleased commits). Any unreleased part can be re-generated until you release it (which means that you tag it with a version tag).

The full recipe is detailled in the doc.

**Comment by tuukkamustonen** [comment]
I mean, if you push a commit to master you can't include that commit in the changelog (because you must update `CHANGELOG.md` or such *before* you commit). With some tweaks (e.g. committing, then generating changelog diff, `git reset --soft HEAD`, applying your diff and committing again) it should be doable.

Definitively a cool feature. Yeah, I should RTFM.

**Comment by vaab** [comment]
Ok, I get what you meant.

Generally people wanting to commit their changelog's are ready for release commit, often, the version information is also modified then. 

Here's a slightly better way than what you proposed to avoid requiring release commits:
1- code
2- commit,
3- generate new changelog
4- read it, tweak it
5- amend the commit to add the changelog
6- push

**Comment by tuukkamustonen** [comment]
I agree, amending feels a bit "safer", good point.

Yeah, normally I update changelog only when releasing. But then, during an iteration the changelog file in the repository is not updated and will not describe what fixes have been implemented. Constantly updating changelog for each commit/merge would introduce a little bit more transparency to the process.
