### ISSUE TITLE
Incremental changelog since given version not working as described

### ISSUE THREAD

**Issue by znegva** [vaab/gitchangelog#81]
Hi,
the README describes:

> ```
> ## will output only tags since 0.0.3 (excluded)
> gitchangelog ^0.0.3
> ```

this isnt working for me, I just get:
`No commits matching given revlist: ^0.0.3`

tested with 
`git version 2.12.2` and `git version 2.11.0 (Apple Git-81)`
using `Python 2.7.13`

but using 
```
gitchangelog 0.0.3..
```
gives the wanted result.

Maybe it is a bug or depends on the git version or maybe just the docs shall be changed/expanded.

**Comment by vaab** [comment]
Ah yes. This was working in ``2.5.1``, but I think it is better to stick to ``git rev-list [REVS]`` syntax behavior which is the current behavior since ``3.0.0+`` .

For information, the commit that breaks that behavior between ``2.5.1`` and ``3.0.0`` is: 11ae52093d950924ce0fdb2da4107980602d95fb and more specifically the additions of the 2 lines:
```
if revlist and not revs:
    die("No commits matching given revlist: %s" % (" ".join(revlist), ))
```
I should add, that this test protected from empty commit lists that could result of other bad REV spec that would result in no commit to be selected.

Corrected the ``README.rst`` accordingly, and added a substantial changelog message mentionnig API changes (because this was an undocumented CLI API change...)

Thanks for spotting this.

**Comment by vaab** [comment]
Argl, I need to verify if what's written right after in the README is valid (there's a missing HEAD again). I don't have time right now.
